services:
    db:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_DB=otus_db
            - POSTGRES_USER=otus
            - POSTGRES_PASSWORD=otus
        ports:
            - 5432:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5
    app:
        build:
          context: .
          dockerfile: Dockerfile
        env_file:
          - .env
        command: >
          sh -c "export PYTHONPATH=src && python -m alembic upgrade head && python -m litestar --app apps.base_app.app:app run --host 0.0.0.0 --port 8000 --debug"
        ports:
          - "8000:8000"
        depends_on:
          db:
            condition: service_healthy
        restart: always