"""add password col

Revision ID: ac9db9acdd47
Revises: 88f1ab9238c5
Create Date: 2024-06-15 23:29:47.898937

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac9db9acdd47"
down_revision: Union[str, None] = "88f1ab9238c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.create_unique_constraint(op.f("uq__users__id"), "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq__users__id"), "users", type_="unique")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
